export enum Icon {
  Image = require('../assets/icons/image-icon.png'),
  Video = require('../assets/icons/video-icon.png'),
  Product = require('../assets/icons/product-icon.png'),
  Heart = require('../assets/icons/heart-icon.png'),
  Comment = require('../assets/icons/comment-icon.png'),
  Hearts = require('../assets/icons/Heart.png'),
  Comments = require('../assets/icons/Comment.png'),
  Send = require('../assets/icons/IconSend.png'),
  ArrowLeft = require('../assets/icons/arrow-left.png'),
  Xicon = require('../assets/icons/x.png'),
  Option = require('../assets/icons/Vector.png'),
  Edit = require('../assets/icons/Edit.png'),
  Delete = require('../assets/icons/Trash.png'),
}
